# Classifying Gestures of Sign Language - Demo.

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
# import seaborn as sns
import matplotlib.pyplot as plt

# from subprocess import check_output

# Loading the Dataset

In [2]:
df = pd.read_csv('2022-03-18 17-07-41 training data.csv',header = None)

In [3]:
# add column names. No need if the origin files have.
fin_info = [i for i in range(df.shape[1]-2)]
df.columns = ["Timestamp","Letter"]+fin_info

In [4]:
df_ori = df.copy()

df_aug=df.copy()
df_ori

,Timestamp,Letter,0,1,2,3,4,5,6,7,...,224,225,226,227,228,229,230,231,232,233
0,2022-03-18 17:07:53.105000,B,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.265,4.844,-14.330,-2.847,5.019,-14.241,-1.762,0.0,0.0,0.0
1,2022-03-18 17:08:00.102000,C,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.971,2.461,-10.511,-6.560,2.749,-11.556,-6.355,0.0,0.0,0.0
2,2022-03-18 17:08:01.109000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.356,4.928,-14.201,-2.877,5.152,-14.216,-1.798,0.0,0.0,0.0
3,2022-03-18 17:08:02.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.988,4.131,-14.466,-2.573,4.332,-14.388,-1.491,0.0,0.0,0.0
4,2022-03-18 17:08:03.108000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.083,4.133,-14.441,-2.652,4.338,-14.395,-1.570,0.0,0.0,0.0
5,2022-03-18 17:08:04.101000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-4.101,4.315,-13.648,-4.379,4.629,-14.038,-3.397,0.0,0.0,0.0
6,2022-03-18 17:08:09.098000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-4.205,1.834,-6.621,-3.865,1.367,-6.586,-4.863,0.0,0.0,0.0
7,2022-03-18 17:08:11.102000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.184,4.278,-14.488,-1.792,4.474,-14.365,-0.714,0.0,0.0,0.0
8,2022-03-18 17:08:12.100000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.389,4.248,-14.519,-2.009,4.437,-14.368,-0.934,0.0,0.0,0.0
9,2022-03-18 17:08:17.106000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.521,4.293,-12.986,-3.491,4.655,-13.743,-2.776,0.0,0.0,0.0
10,2022-03-18 17:08:18.105000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.106,4.642,-14.468,-1.735,4.815,-14.291,-0.660,0.0,0.0,0.0
11,2022-03-18 17:08:19.095000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.230,4.373,-14.467,-1.832,4.569,-14.353,-0.754,0.0,0.0,0.0
12,2022-03-18 17:08:20.098000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.738,4.497,-14.400,-2.301,4.703,-14.358,-1.219,0.0,0.0,0.0
13,2022-03-18 17:08:21.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.759,5.604,-13.531,-4.106,5.919,-13.780,-3.079,0.0,0.0,0.0
14,2022-03-18 17:08:22.100000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.754,5.903,-13.803,-3.212,6.139,-13.898,-2.140,0.0,0.0,0.0
15,2022-03-18 17:08:27.096000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.526,4.181,-14.477,-2.107,4.383,-14.410,-1.026,0.0,0.0,0.0
16,2022-03-18 17:08:28.103000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.467,4.149,-14.506,-2.070,4.348,-14.394,-0.991,0.0,0.0,0.0
17,2022-03-18 17:08:32.099000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.904,2.520,-7.622,-2.925,1.822,-7.220,-3.678,0.0,0.0,0.0
18,2022-03-18 17:08:33.099000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.073,5.151,-14.091,-2.530,5.395,-14.215,-1.462,0.0,0.0,0.0
19,2022-03-18 17:08:34.103000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-0.545,4.264,-14.529,-1.206,4.438,-14.291,-0.144,0.0,0.0,0.0
20,2022-03-18 17:08:35.106000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-0.651,4.216,-14.537,-1.307,4.395,-14.311,-0.243,0.0,0.0,0.0
21,2022-03-18 17:08:36.105000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.585,1.569,-5.225,-3.374,1.080,-4.945,-4.321,0.0,0.0,0.0
22,2022-03-18 17:08:40.104000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-4.370,1.879,-6.545,-4.063,1.389,-6.448,-5.045,0.0,0.0,0.0
23,2022-03-18 17:08:41.107000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.138,1.557,-5.465,-3.094,0.973,-5.025,-3.919,0.0,0.0,0.0
24,2022-03-18 17:08:42.094000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-0.871,4.203,-14.491,-1.483,4.391,-14.367,-0.404,0.0,0.0,0.0
25,2022-03-18 17:08:43.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.333,4.079,-14.524,-1.938,4.272,-14.411,-0.859,0.0,0.0,0.0
26,2022-03-18 17:08:45.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.283,5.133,-13.947,-3.735,5.369,-14.071,-2.666,0.0,0.0,0.0
27,2022-03-18 17:08:46.104000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.428,5.006,-13.966,-3.932,5.207,-14.011,-2.849,0.0,0.0,0.0
28,2022-03-18 17:08:47.107000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.867,5.136,-13.752,-4.330,5.358,-13.855,-3.255,0.0,0.0,0.0
29,2022-03-18 17:08:49.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.213,4.810,-14.413,-1.817,4.982,-14.288,-0.736,0.0,0.0,0.0
30,2022-03-18 17:08:50.100000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.268,4.875,-14.370,-1.857,5.058,-14.273,-0.774,0.0,0.0,0.0
31,2022-03-18 17:08:51.100000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.330,5.172,-14.322,-1.932,5.339,-14.192,-0.850,0.0,0.0,0.0
32,2022-03-18 17:08:53.108000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.211,3.963,-12.411,-6.320,4.337,-12.985,-5.456,0.0,0.0,0.0
33,2022-03-18 17:08:54.105000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.809,3.231,-11.766,-6.747,3.595,-12.540,-6.051,0.0,0.0,0.0
34,2022-03-18 17:08:55.098000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-5.716,3.417,-12.310,-5.565,3.766,-13.180,-4.984,0.0,0.0,0.0
35,2022-03-18 17:08:56.100000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.270,4.573,-14.467,-1.893,4.755,-14.302,-0.818,0.0,0.0,0.0
36,2022-03-18 17:08:57.101000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.933,4.948,-14.310,-2.496,5.142,-14.256,-1.412,0.0,0.0,0.0
37,2022-03-18 17:08:58.105000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.787,4.872,-14.338,-2.352,5.067,-14.282,-1.269,0.0,0.0,0.0
38,2022-03-18 17:09:01.098000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-4.049,1.589,-5.653,-3.781,1.109,-5.473,-4.756,0.0,0.0,0.0
39,2022-03-18 17:09:02.101000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-4.330,1.631,-5.848,-4.016,1.168,-5.736,-5.010,0.0,0.0,0.0
40,2022-03-18 17:09:05.107000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.461,1.780,-6.290,-3.267,1.242,-6.050,-4.199,0.0,0.0,0.0
41,2022-03-18 17:09:06.093000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.391,1.704,-6.307,-3.208,1.155,-6.071,-4.135,0.0,0.0,0.0
42,2022-03-18 17:09:07.098000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.337,1.712,-6.281,-3.165,1.159,-6.030,-4.085,0.0,0.0,0.0
43,2022-03-18 17:09:10.104000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.833,1.877,-5.888,-3.633,1.365,-5.597,-4.565,0.0,0.0,0.0
44,2022-03-18 17:09:13.099000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.741,2.112,-6.856,-2.767,1.444,-6.416,-3.525,0.0,0.0,0.0
45,2022-03-18 17:09:14.100000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.173,2.434,-9.134,-5.476,2.548,-10.065,-6.055,0.0,0.0,0.0
46,2022-03-18 17:09:16.105000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-5.459,4.883,-11.025,-5.020,5.577,-11.864,-4.851,0.0,0.0,0.0
47,2022-03-18 17:09:17.108000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-5.707,4.565,-10.977,-5.236,5.215,-11.860,-5.127,0.0,0.0,0.0
48,2022-03-18 17:09:18.093000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.663,1.821,-7.833,-5.939,1.968,-8.628,-6.688,0.0,0.0,0.0
49,2022-03-18 17:09:19.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.371,2.397,-8.892,-5.663,2.626,-9.796,-6.252,0.0,0.0,0.0
50,2022-03-18 17:09:20.102000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-5.464,1.918,-7.703,-4.795,1.843,-8.329,-5.699,0.0,0.0,0.0
51,2022-03-18 17:09:21.102000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-5.798,2.069,-8.243,-5.102,2.005,-9.029,-5.872,0.0,0.0,0.0
52,2022-03-18 17:09:22.106000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.005,2.089,-8.366,-5.303,2.064,-9.191,-6.035,0.0,0.0,0.0
53,2022-03-18 17:09:23.096000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.244,1.909,-6.746,-3.107,1.315,-6.490,-4.000,0.0,0.0,0.0
54,2022-03-18 17:09:24.102000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.441,2.044,-6.728,-3.176,1.532,-6.574,-4.140,0.0,0.0,0.0
55,2022-03-18 17:09:25.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.224,2.898,-12.357,-6.297,3.175,-13.032,-5.471,0.0,0.0,0.0
56,2022-03-18 17:09:26.110000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.773,4.740,-13.887,-4.245,4.959,-13.989,-3.169,0.0,0.0,0.0
57,2022-03-18 17:09:27.107000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-7.554,2.552,-10.604,-7.313,2.873,-11.543,-6.833,0.0,0.0,0.0

In [5]:
df.head()

,Timestamp,Letter,0,1,2,3,4,5,6,7,...,224,225,226,227,228,229,230,231,232,233
0,2022-03-18 17:07:53.105000,B,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.265,4.844,-14.330,-2.847,5.019,-14.241,-1.762,0.0,0.0,0.0
1,2022-03-18 17:08:00.102000,C,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.971,2.461,-10.511,-6.560,2.749,-11.556,-6.355,0.0,0.0,0.0
2,2022-03-18 17:08:01.109000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.356,4.928,-14.201,-2.877,5.152,-14.216,-1.798,0.0,0.0,0.0
3,2022-03-18 17:08:02.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.988,4.131,-14.466,-2.573,4.332,-14.388,-1.491,0.0,0.0,0.0
4,2022-03-18 17:08:03.108000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.083,4.133,-14.441,-2.652,4.338,-14.395,-1.570,0.0,0.0,0.0

In [6]:
df.tail()

,Timestamp,Letter,0,1,2,3,4,5,6,7,...,224,225,226,227,228,229,230,231,232,233
53,2022-03-18 17:09:23.096000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.244,1.909,-6.746,-3.107,1.315,-6.490,-4.000,0.0,0.0,0.0
54,2022-03-18 17:09:24.102000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.441,2.044,-6.728,-3.176,1.532,-6.574,-4.140,0.0,0.0,0.0
55,2022-03-18 17:09:25.097000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-6.224,2.898,-12.357,-6.297,3.175,-13.032,-5.471,0.0,0.0,0.0
56,2022-03-18 17:09:26.110000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.773,4.740,-13.887,-4.245,4.959,-13.989,-3.169,0.0,0.0,0.0
57,2022-03-18 17:09:27.107000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-7.554,2.552,-10.604,-7.313,2.873,-11.543,-6.833,0.0,0.0,0.0

In [7]:
df.sample(5)

,Timestamp,Letter,0,1,2,3,4,5,6,7,...,224,225,226,227,228,229,230,231,232,233
43,2022-03-18 17:09:10.104000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.833,1.877,-5.888,-3.633,1.365,-5.597,-4.565,0.0,0.0,0.0
18,2022-03-18 17:08:33.099000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-2.073,5.151,-14.091,-2.530,5.395,-14.215,-1.462,0.0,0.0,0.0
27,2022-03-18 17:08:46.104000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-3.428,5.006,-13.966,-3.932,5.207,-14.011,-2.849,0.0,0.0,0.0
20,2022-03-18 17:08:35.106000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-0.651,4.216,-14.537,-1.307,4.395,-14.311,-0.243,0.0,0.0,0.0
36,2022-03-18 17:08:57.101000,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,...,-1.933,4.948,-14.310,-2.496,5.142,-14.256,-1.412,0.0,0.0,0.0

In [8]:
df.dtypes

Timestamp     object
Letter        object
0            float64
1            float64
2            float64
              ...
229          float64
230          float64
231          float64
232          float64
233          float64
Length: 236, dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Columns: 236 entries, Timestamp to 233
dtypes: float64(234), object(2)
memory usage: 107.1+ KB

In [10]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,224,225,226,227,228,229,230,231,232,233
count,58.0,58.0,58.0,5.800000e+01,5.800000e+01,5.800000e+01,5.800000e+01,5.800000e+01,5.800000e+01,58.000000,...,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.0,58.0,58.0
mean,0.0,0.0,0.0,-1.050000e+00,-2.007000e+00,-1.155000e+00,-1.050000e+00,-2.007000e+00,-1.155000e+00,-2.353966,...,-3.418034,3.553655,-11.325552,-3.548500,3.594828,-11.458810,-3.227431,0.0,0.0,0.0
std,0.0,0.0,0.0,1.119919e-15,1.791871e-15,6.719517e-16,1.119919e-15,1.791871e-15,6.719517e-16,0.515568,...,1.909167,1.346959,3.441371,1.544964,1.628949,3.470755,2.031838,0.0,0.0,0.0
min,0.0,0.0,0.0,-1.050000e+00,-2.007000e+00,-1.155000e+00,-1.050000e+00,-2.007000e+00,-1.155000e+00,-3.086000,...,-7.554000,1.557000,-14.537000,-7.313000,0.973000,-14.411000,-6.833000,0.0,0.0,0.0
25%,0.0,0.0,0.0,-1.050000e+00,-2.007000e+00,-1.155000e+00,-1.050000e+00,-2.007000e+00,-1.155000e+00,-2.810500,...,-4.360000,2.074000,-14.392500,-4.366750,1.874250,-14.286500,-4.953750,0.0,0.0,0.0
50%,0.0,0.0,0.0,-1.050000e+00,-2.007000e+00,-1.155000e+00,-1.050000e+00,-2.007000e+00,-1.155000e+00,-2.325000,...,-3.364000,4.141000,-13.258500,-3.210000,4.343000,-13.761500,-3.326000,0.0,0.0,0.0
75%,0.0,0.0,0.0,-1.050000e+00,-2.007000e+00,-1.155000e+00,-1.050000e+00,-2.007000e+00,-1.155000e+00,-2.048500,...,-1.750250,4.715500,-7.735500,-2.313750,4.976250,-8.403750,-1.231500,0.0,0.0,0.0
max,0.0,0.0,0.0,-1.050000e+00,-2.007000e+00,-1.155000e+00,-1.050000e+00,-2.007000e+00,-1.155000e+00,-0.894000,...,-0.545000,5.903000,-5.225000,-1.206000,6.139000,-4.945000,-0.144000,0.0,0.0,0.0

# Data Augmentation

In [11]:
# Randomly augment data. No need if we have enough data.
# fit for the first version dataset 
# may need some changes if we update the dataset
aug = 1000
col=df.columns
df_aug=df.copy()

for i in range(aug):
    new_row = [np.concatenate((df_ori.sample(1).values[0,0:2],df_ori.sample(1).values[0,2:] + np.random.normal(0,5)),axis = 0)]
    df_gen = pd.DataFrame(new_row,columns = col)
    df_aug = pd.concat([df_aug,df_gen],ignore_index = True)
# Add more data whose letter is "A", to balance dataset
for i in range(600):
    new_row = [np.concatenate((df_ori.loc[0,:].values[0:2],df_ori.loc[0,:].values[2:] + np.random.normal(0,5)),axis = 0)]
    df_gen = pd.DataFrame(new_row,columns = col)
    df_aug = pd.concat([df_aug,df_gen],ignore_index = True)
    
# Add more data whose letter is "other", to balance dataset 
for i in range(600):
    new_row = [np.concatenate((df_ori.loc[1,:].values[0:2],df_ori.loc[1,:].values[2:] + np.random.normal(0,5)),axis = 0)]
    df_gen = pd.DataFrame(new_row,columns = col)
    df_aug = pd.concat([df_aug,df_gen],ignore_index = True)

In [12]:
df_aug["Letter"].value_counts()

other    1030
B         614
C         614
Name: Letter, dtype: int64

In [13]:
df_aug.drop('Timestamp',axis=1,inplace=True) #dropping the Id column as it is unecessary, axis=1 specifies that it should be column wise, inplace =1 means the changes should be reflected into the dataframe

In [14]:
df_aug.head()

,Letter,0,1,2,3,4,5,6,7,8,...,224,225,226,227,228,229,230,231,232,233
0,B,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,-1.155,...,-2.265,4.844,-14.330,-2.847,5.019,-14.241,-1.762,0.0,0.0,0.0
1,C,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,-1.155,...,-6.971,2.461,-10.511,-6.560,2.749,-11.556,-6.355,0.0,0.0,0.0
2,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,-1.155,...,-2.356,4.928,-14.201,-2.877,5.152,-14.216,-1.798,0.0,0.0,0.0
3,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,-1.155,...,-1.988,4.131,-14.466,-2.573,4.332,-14.388,-1.491,0.0,0.0,0.0
4,other,0.0,0.0,0.0,-1.05,-2.007,-1.155,-1.05,-2.007,-1.155,...,-2.083,4.133,-14.441,-2.652,4.338,-14.395,-1.570,0.0,0.0,0.0

In [15]:
# importing all the necessary packages to use the various classification algorithms
from sklearn.linear_model import LogisticRegression  # for Logistic Regression algorithm
from sklearn.model_selection import train_test_split #to split the dataset for training and testing
from sklearn.neighbors import KNeighborsClassifier  # for K nearest neighbours
from sklearn import svm  #for Support Vector Machine (SVM) Algorithm
from sklearn import metrics #for checking the model accuracy
from sklearn.tree import DecisionTreeClassifier #for using Decision Tree Algoithm
from sklearn.metrics import classification_report
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
# from sklearn.metrics import classification_report, confusion_matrix

In [16]:
train, test = train_test_split(df_aug, test_size = 0.3)# in this our main data is split into train and test
# the attribute test_size=0.3 splits the data into 70% and 30% ratio. train=70% and test=30%
print(train.shape)
print(test.shape)

(1580, 235)
(678, 235)

In [17]:
train_X = train[fin_info]# taking the training data features
train_y=train.Letter# output of our training data
test_X= test[fin_info] # taking test data features
test_y =test.Letter   #output value of test data

In [18]:
from sklearn import preprocessing
mm_scaler = preprocessing.RobustScaler()
mm_scaler = preprocessing.MinMaxScaler()
train_X = mm_scaler.fit_transform(train_X)
test_X = mm_scaler.transform(test_X)

In [19]:
train_X

array([[0.55919976, 0.55919976, 0.55919976, ..., 0.55919976, 0.55919976,
        0.55919976],
       [0.60532204, 0.60532204, 0.60532204, ..., 0.60532204, 0.60532204,
        0.60532204],
       [0.5965699 , 0.5965699 , 0.5965699 , ..., 0.5965699 , 0.5965699 ,
        0.5965699 ],
       ...,
       [0.45900774, 0.45900774, 0.45900774, ..., 0.45900774, 0.45900774,
        0.45900774],
       [0.46068703, 0.46068703, 0.46068703, ..., 0.46068703, 0.46068703,
        0.46068703],
       [0.47465413, 0.47465413, 0.47465413, ..., 0.47465413, 0.47465413,
        0.47465413]])

In [20]:
train_y.head()

1646        B
670     other
2165        C
1668        C
1009    other
Name: Letter, dtype: object

In [21]:
test_X

array([[0.45770947, 0.45770947, 0.45770947, ..., 0.45770947, 0.45770947,
        0.45770947],
       [0.32952738, 0.32952738, 0.32952738, ..., 0.32952738, 0.32952738,
        0.32952738],
       [0.45973196, 0.45973196, 0.45973196, ..., 0.45973196, 0.45973196,
        0.45973196],
       ...,
       [0.62632717, 0.62632717, 0.62632717, ..., 0.62632717, 0.62632717,
        0.62632717],
       [0.27598248, 0.27598248, 0.27598248, ..., 0.27598248, 0.27598248,
        0.27598248],
       [0.65416381, 0.65416381, 0.65416381, ..., 0.65416381, 0.65416381,
        0.65416381]])

In [22]:
test_y.head()

470     other
1850        C
229     other
1735        C
1705        C
Name: Letter, dtype: object

# Machine Learning Model

In [23]:
# Train the model, return the best model based on the test data
def train(train_X,train_y,test_X,test_y):
    lr = LogisticRegression(max_iter = 1000)
    lr.fit(train_X,train_y)
    lr_pre=lr.predict(test_X)
    lr_acc = metrics.accuracy_score(lr_pre,test_y)
    print('The accuracy of the Logistic Regression is',lr_acc)
    dt=DecisionTreeClassifier()
    dt.fit(train_X,train_y)
    dt_pre=dt.predict(test_X)
    dt_acc = metrics.accuracy_score(dt_pre,test_y)
    print('The accuracy of the Decision Tree is',dt_acc)
    rf = RandomForestClassifier(n_estimators=1000, criterion='entropy', random_state=None, bootstrap=True)
    rf.fit(train_X,train_y)
    rf_pre=rf.predict(test_X)
    rf_acc = metrics.accuracy_score(rf_pre,test_y)
    print('The accuracy of the Random Forest is',rf_acc)    
    knn=KNeighborsClassifier(n_neighbors=3) #this examines 3 neighbours for putting the new data into a class
    knn.fit(train_X,train_y)
    knn_pre=knn.predict(test_X)
    knn_acc = metrics.accuracy_score(knn_pre,test_y)
    print('The accuracy of the KNN is',knn_acc)    
    svm=SVC(probability=True)
    svm.fit(train_X, train_y)
    svm_pre=svm.predict(test_X)
    svm_acc = metrics.accuracy_score(svm_pre,test_y)
    print('The accuracy of the SVM is',svm_acc)
    mlp=MLPClassifier(hidden_layer_sizes=(128,64,32),random_state = 1)
    mlp.fit(train_X,train_y)
    mlp_pre=mlp.predict(test_X)
    mlp_acc = metrics.accuracy_score(mlp_pre,test_y)
    print('The accuracy of the MLP is',mlp_acc)
    dir = {lr:lr_acc,dt:dt_acc,rf:rf_acc,knn:knn_acc,svm:svm_acc,mlp:mlp_acc}
    best = 0
    model = None
    for i in dir.keys():
        if dir[i]>best:
            best = dir[i]
            model = i
    return model

In [24]:
# train the model
model = train(train_X,train_y,test_X,test_y)

The accuracy of the Logistic Regression is 0.9690265486725663
The accuracy of the Decision Tree is 0.9292035398230089
The accuracy of the Random Forest is 0.9498525073746312
The accuracy of the KNN is 0.9557522123893806
The accuracy of the SVM is 0.9660766961651918
The accuracy of the MLP is 0.967551622418879

In [25]:
def pred(model, X):
    prediction=model.predict_proba(X.reshape(1, -1))
    cl = model.classes_
    pro = prediction[0]
    head=""
    internal = ""
    for i in range(len(cl)):
        if i == 0:
            head = "{}:{}".format(cl[i],pro[i])
        else:
            internal = internal + (" ;{}:{}".format(cl[i],pro[i]))
        
    return "Probabilities: {" +head+internal+"}."

In [31]:
X = test_X[1]
pred(model, X)

'Probabilities: {B:0.007320740871000974 ;C:0.9071781490144448 ;other:0.08550111011455426}.'

In [27]:

# # Logistic Regression
# def LR(train_X,train_y,test_X,test_y,X = test_X[0]):
#     model = LogisticRegression(max_iter = 1000)
#     model.fit(train_X,train_y)
#     prediction=model.predict(test_X)

#     print('The accuracy of the Logistic Regression is',metrics.accuracy_score(prediction,test_y))

# #     print(sklearn.metrics.confusion_matrix(test_y,prediction))

# #     print(classification_report(test_y, prediction))

#     pro=model.predict_proba(X.reshape(1, -1))

#     return pro[0]

# # Decision Tree Classifier
# def DT(train_X,train_y,test_X,test_y,X = test_X[0]):
#     model=DecisionTreeClassifier()
#     model.fit(train_X,train_y)
#     prediction=model.predict(test_X)
#     print('The accuracy of the Decision Tree is',metrics.accuracy_score(prediction,test_y))
# #     print(sklearn.metrics.confusion_matrix(test_y,prediction))
# #     print(classification_report(test_y, prediction))
#     pro=model.predict_proba(X.reshape(1, -1))
#     return pro[0]

# # Random Forest Classifer
# def RF(train_X,train_y,test_X,test_y,X = test_X[0]):
#     model = RandomForestClassifier(n_estimators=1000, criterion='entropy', random_state=None, bootstrap=True)
#     model.fit(train_X,train_y)
#     prediction=model.predict(test_X)
#     print('The accuracy of the Random Forest is',metrics.accuracy_score(prediction,test_y))
# #     print(sklearn.metrics.confusion_matrix(test_y,prediction))
# #     print(classification_report(test_y, prediction))
#     pro=model.predict_proba(X.reshape(1, -1))
#     return pro[0]

# # K-Nearest Neighbor
# def KNN(train_X,train_y,test_X,test_y,X = test_X[0]):
#     model=KNeighborsClassifier(n_neighbors=3) #this examines 3 neighbours for putting the new data into a class
#     model.fit(train_X,train_y)
#     prediction=model.predict(test_X)
#     print('The accuracy of the KNN is',metrics.accuracy_score(prediction,test_y))
# #     print(sklearn.metrics.confusion_matrix(test_y,prediction))
# #     print(classification_report(test_y, prediction))

#     pro=model.predict_proba(X.reshape(1, -1))
#     return pro[0]

# # Support Vector Machine
# def SVM(train_X,train_y,test_X,test_y,X = test_X[0]):

#     model=SVC(probability=True)
#     model.fit(train_X, train_y)
#     prediction=model.predict(test_X)
#     print('The accuracy of the SVM is',metrics.accuracy_score(prediction,test_y))
# #     print(confusion_matrix(test_y,prediction))

# #     print(classification_report(test_y, prediction))

#     pro=model.predict_proba(X.reshape(1, -1))
#     return pro[0]

# # Multilayer Perceptron
# def MLP(train_X,train_y,test_X,test_y,X = test_X[0]):
#     model=MLPClassifier(hidden_layer_sizes=(128,64,32),random_state = 1)
#     model.fit(train_X,train_y)
#     prediction=model.predict(test_X)
#     print('The accuracy of the MLP is',metrics.accuracy_score(prediction,test_y))
# #     print(sklearn.metrics.confusion_matrix(test_y,prediction))
# #     print(classification_report(test_y, prediction))
#     pro=model.predict_proba(X.reshape(1, -1))
#     return pro[0]